title: Andy's Test Blog
author: Andy
email: your-email@domain.com
description: I'm posting this blog in order to learn how to use Github pages with jekyII.
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
